# 静的解析ツールを複数管理するための設定
# 静的解析でエラーが報告されたとき、PR上で該当行にコメントしてくれる
name: golang-ci
on:
  pull_request:
    paths:
      - "**.go"
      - .github/workflows/golangci.yml
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory actions/checkout@v3
        uses: actions/checkout@v3
      - name: go-langci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=./.golangci.yml ./..."
          fail_on_error: true
          reporter: "github-pr-review"
